# Exercício 1: Carregando e analisando um DataSet

## Dados Estação Cuiabá 2003

In [1]:
import pandas as pd

# Carrega o arquivo csv

dataframe2003 = pd.read_csv('./datasets/INMET_CO_MT_A901_CUIABA_01-01-2003_A_31-12-2003.CSV', sep=';', encoding='ISO-8859-1' , decimal = ',')

# Exibe os primeiros registros do dataframe
dataframe2003.head()
#dataframe2003

,DATA,HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (MM)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/mý),"TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)",TEMPERATURA DO PONTO DE ORVALHO (øC),TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC),TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇO HORARIA (gr) (ø (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
0,01/01/2003,00:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,24.3,23.3,24.7,24.3,23.4,-9999.0,94,92,94,-9999,-9999.0,-9999.0
1,01/01/2003,01:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,24.7,23.3,24.7,24.3,23.4,-9999.0,94,92,92,-9999,-9999.0,-9999.0
2,01/01/2003,02:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,24.4,23.2,24.7,24.4,23.4,-9999.0,93,91,93,-9999,-9999.0,-9999.0
3,01/01/2003,03:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,24.1,23.2,24.9,24.1,23.5,-9999.0,95,92,95,-9999,-9999.0,-9999.0
4,01/01/2003,04:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,24.5,23.4,24.6,24.1,23.5,-9999.0,95,93,94,-9999,-9999.0,-9999.0

## Dados Estação Cuiabá 2013

In [2]:
# Carregar o arquivo csv

dataframe2013 = pd.read_csv('./datasets/INMET_CO_MT_A901_CUIABA_01-01-2013_A_31-12-2013.CSV', sep=';', encoding='ISO-8859-1', decimal = ',')

# Exibe os primeiros registros do dataframe
dataframe2013.head()

,DATA,HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/mý),"TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)",TEMPERATURA DO PONTO DE ORVALHO (øC),TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC),TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇO HORARIA (gr) (ø (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
0,01/01/2013,00:00,0.4,983.5,983.5,982.1,-9999.0,26.1,21.9,28.1,26.1,22.0,20.7,78,64,78,145,4.3,2.1
1,01/01/2013,01:00,1.2,983.9,984.0,983.5,-9999.0,24.7,22.7,26.1,24.5,22.9,22.2,89,78,89,184,4.0,1.4
2,01/01/2013,02:00,0.4,984.4,984.5,983.9,-9999.0,24.5,22.8,24.9,24.5,23.2,22.5,91,88,91,247,3.7,1.6
3,01/01/2013,03:00,0.0,984.9,985.0,984.4,-9999.0,24.4,22.9,24.5,24.2,22.9,22.5,92,90,92,98,3.5,1.9
4,01/01/2013,04:00,0.0,984.3,984.9,984.3,-9999.0,24.4,22.9,24.4,24.2,23.0,22.8,92,91,91,123,3.5,1.2

# Dados Estação Cuiabá 2023

In [3]:
# Carregar o arquivo csv

dataframe2023 = pd.read_csv('./datasets/INMET_CO_MT_A901_CUIABA_01-01-2023_A_31-12-2023.CSV', sep=';', encoding='ISO-8859-1', decimal = ',')

# Exibe os primeiros registros do dataframe
dataframe2023.head()

,DATA,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/mý),"TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)",TEMPERATURA DO PONTO DE ORVALHO (øC),TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC),TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇO HORARIA (gr) (ø (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
0,01/01/2023,0000 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,01/01/2023,0100 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01/01/2023,0200 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01/01/2023,0300 UTC,0.0,990.5,990.5,990.4,NaN,27.5,20.6,27.9,27.5,20.6,20.2,66.0,63.0,66.0,NaN,NaN,NaN
4,01/01/2023,0400 UTC,0.0,990.2,990.5,990.2,NaN,27.3,20.2,27.8,27.3,20.7,20.2,66.0,65.0,65.0,NaN,NaN,NaN

In [4]:
type(dataframe2003)

pandas.core.frame.DataFrame

In [5]:
dataframe2003.shape

(8760, 19)

In [6]:
#Renomeando coluna do datasets
dataframe2023.rename(columns={'Hora UTC':'HORA (UTC)', 'RADIACAO GLOBAL (Kj/mý)': 'RADIACAO GLOBAL (KJ/mý)'}, inplace=True)
dataframe2003.rename(columns={'PRECIPITAÇÃO TOTAL, HORÁRIO (MM)': 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'},inplace=True)
#print(dataframe2023.columns.values)

In [7]:
#Convertendo coluna DATA para datetime
dataframe2003['DATA'] = pd.to_datetime(dataframe2003['DATA'], format='%d/%m/%Y', errors='coerce').dt.strftime('%Y/%m/%d')
dataframe2013['DATA'] = pd.to_datetime(dataframe2013['DATA'], format='%d/%m/%Y', errors='coerce').dt.strftime('%Y/%m/%d')
dataframe2023['DATA'] = pd.to_datetime(dataframe2023['DATA'], format='%d/%m/%Y', errors='coerce').dt.strftime('%Y/%m/%d')

In [8]:
df_concat = pd.concat([dataframe2003, dataframe2013, dataframe2023])
df_concat['DATA'] = pd.to_datetime(df_concat['DATA'])  
df_concat['Ano'] = df_concat['DATA'].dt.year
df_concat['Mês'] = df_concat['DATA'].dt.month
df_concat['Dia'] = df_concat['DATA'].dt.day

multiIndex = pd.MultiIndex.from_frame(df_concat[['Ano', 'Mês', 'Dia']])

df_concat.set_index(multiIndex, inplace=True)
df_concat.drop('DATA', axis=1, inplace=True)
df_concat = df_concat.iloc[:, :-3]

df_concat

             HORA (UTC)  PRECIPITAÇÃO TOTAL, HORÁRIO (mm)  \
Ano  Mês Dia
2003 1   1        00:00                           -9999.0
         1        01:00                           -9999.0
         1        02:00                           -9999.0
         1        03:00                           -9999.0
         1        04:00                           -9999.0
...                 ...                               ...
2023 12  31    1900 UTC                               0.0
         31    2000 UTC                               0.0
         31    2100 UTC                               0.0
         31    2200 UTC                               0.0
         31    2300 UTC                               NaN

              PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)  \
Ano  Mês Dia
2003 1   1                                              -9999.0
         1                                              -9999.0
         1                                              -9999.0
         1                                              -9999.0
         1                                              -9999.0
...                                                         ...
2023 12  31                                               987.4
         31                                               986.7
         31                                               986.8
         31                                               986.9
         31                                                 NaN

              PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)  \
Ano  Mês Dia
2003 1   1                                            -9999.0
         1                                            -9999.0
         1                                            -9999.0
         1                                            -9999.0
         1                                            -9999.0
...                                                       ...
2023 12  31                                             988.8
         31                                             987.4
         31                                             986.8
         31                                             987.0
         31                                               NaN

              PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)  \
Ano  Mês Dia
2003 1   1                                             -9999.0
         1                                             -9999.0
         1                                             -9999.0
         1                                             -9999.0
         1                                             -9999.0
...                                                        ...
2023 12  31                                              987.4
         31                                              986.7
         31                                              986.6
         31                                              986.8
         31                                                NaN

              RADIACAO GLOBAL (KJ/mý)  \
Ano  Mês Dia
2003 1   1                    -9999.0
         1                    -9999.0
         1                    -9999.0
         1                    -9999.0
         1                    -9999.0
...                               ...
2023 12  31                    2575.3
         31                    1760.8
         31                    1127.5
         31                     490.1
         31                       NaN

              TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)  \
Ano  Mês Dia
2003 1   1                                            24.3
         1                                            24.7
         1                                            24.4
         1                                            24.1
         1                                            24.5
...                                                    ...
2023 12  31                                           34.4
         31                                           33.4
         31                                           32.5
         31                                           30.8
         31                                            NaN

              TEMPERATURA DO PONTO DE ORVALHO (øC)  \
Ano  Mês Dia
2003 1   1                                    23.3
         1                                    23.3
         1                                    23.2
         1                                    23.2
         1                                    23.4
...                                            ...
2023 12  31                                   19.4
         31                                   18.0
         31                                   21.8
         31                                   21.8
         31                                    NaN

              TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)  \
Ano  Mês Dia
2003 1   1                                          24.7
         1                                          24.7
         1                                          24.7
         1                                          24.9
         1                                          24.6
...                                                  ...
2023 12  31                                         35.2
         31                                         35.0
         31                                         33.9
         31                                         32.7
         31                                          NaN

              TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)  \
Ano  Mês Dia
2003 1   1                                          24.3
         1                                          24.3
         1                                          24.4
         1                                          24.1
         1                                          24.1
...                                                  ...
2023 12  31                                         33.9
         31                                         33.3
         31                                         32.1
         31                                         30.8
         31                                          NaN

              TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)  \
Ano  Mês Dia
2003 1   1                                                23.4
         1                                                23.4
         1                                                23.4
         1                                                23.5
         1                                                23.5
...                                                        ...
2023 12  31                                               20.6
         31                                               19.7
         31                                               22.0
         31                                               21.9
         31                                                NaN

              TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)  \
Ano  Mês Dia
2003 1   1                                             -9999.0
         1                                             -9999.0
         1                                             -9999.0
         1                                             -9999.0
         1                                             -9999.0
...                                                        ...
2023 12  31                                               19.1
         31                                               17.9
         31                                               18.0
         31                                               21.3
         31                                                NaN

              UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)  \
Ano  Mês Dia
2003 1   1                                        94.0
         1                                        94.0
         1                                        93.0
         1                                        95.0
         1                                        95.0
...                                                ...
2023 12  31                                       45.0
         31                                       42.0
         31                                       55.0
         31                                       59.0
         31                                        NaN

              UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)  \
Ano  Mês Dia
2003 1   1                                        92.0
         1                                        92.0
         1                                        91.0
         1                                        92.0
         1                                        93.0
...                                                ...
2023 12  31                                       40.0
         31                                       39.0
         31                                       40.0
         31                                       52.0
         31                                        NaN

              UMIDADE RELATIVA DO AR, HORARIA (%)  \
Ano  Mês Dia
2003 1   1                                   94.0
         1                                   92.0
         1                                   93.0
         1                                   95.0
         1                                   94.0
...                                           ...
2023 12  31                                  41.0
         31                                  40.0
         31                                  53.0
         31                                  59.0
         31                                   NaN

              VENTO, DIREÇO HORARIA (gr) (ø (gr))  \
Ano  Mês Dia
2003 1   1                                 -9999.0
         1                                 -9999.0
         1                                 -9999.0
         1                                 -9999.0
         1                                 -9999.0
...                                            ...
2023 12  31                                  320.0
         31                                  339.0
         31                                  105.0
         31                                   96.0
         31                                    NaN

              VENTO, RAJADA MAXIMA (m/s)  VENTO, VELOCIDADE HORARIA (m/s)
Ano  Mês Dia
2003 1   1                       -9999.0                          -9999.0
         1                       -9999.0                          -9999.0
         1                       -9999.0                          -9999.0
         1                       -9999.0                          -9999.0
         1                       -9999.0                          -9999.0
...                                  ...                              ...
2023 12  31                          6.6                              3.0
         31                          7.0                              3.4
         31                          6.0                              2.0
         31                          4.0                              1.5
         31                          NaN                              NaN

[26280 rows x 18 columns]

2. Construa um novo DataFrame modificando o anterior para utiliza um MultiIndex como colunas contendo os parâmetros agrupados (precipitações, pressão, radiação, temperatura, umidade, velocidade do vento )

In [9]:
df_concat.columns.tolist()
colunas = [('HORA (UTC)',''),
 ('PRECIPITAÇÃO','PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'),
 ('PRESSAO','PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)'),
 ('PRESSAO','PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)'),
 ('PRESSAO','PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)'),
 ('RADIACAO','RADIACAO GLOBAL (KJ/mý)'),
 ('TEMPERATURA','TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)'),
 ('TEMPERATURA','TEMPERATURA DO PONTO DE ORVALHO (øC)'),
 ('TEMPERATURA','TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)'),
 ('TEMPERATURA','TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)'),
 ('TEMPERATURA','TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)'),
 ('TEMPERATURA','TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)'),
 ('UMIDADE','UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)'),
 ('UMIDADE','UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)'),
 ('UMIDADE','UMIDADE RELATIVA DO AR, HORARIA (%)'),
 ('VENTO','VENTO, DIRE\x80ÇO HORARIA (gr) (ø (gr))'),
 ('VENTO','VENTO, RAJADA MAXIMA (m/s)'),
 ('VENTO','VENTO, VELOCIDADE HORARIA (m/s)')]

#tuples1 = [df_concat{'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'}],
df_concat.columns = pd.MultiIndex.from_tuples(colunas)
df_concat

             HORA (UTC)                     PRECIPITAÇÃO  \
                        PRECIPITAÇÃO TOTAL, HORÁRIO (mm)
Ano  Mês Dia
2003 1   1        00:00                          -9999.0
         1        01:00                          -9999.0
         1        02:00                          -9999.0
         1        03:00                          -9999.0
         1        04:00                          -9999.0
...                 ...                              ...
2023 12  31    1900 UTC                              0.0
         31    2000 UTC                              0.0
         31    2100 UTC                              0.0
         31    2200 UTC                              0.0
         31    2300 UTC                              NaN

                                                           PRESSAO  \
             PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)
Ano  Mês Dia
2003 1   1                                              -9999.0
         1                                              -9999.0
         1                                              -9999.0
         1                                              -9999.0
         1                                              -9999.0
...                                                         ...
2023 12  31                                               987.4
         31                                               986.7
         31                                               986.8
         31                                               986.9
         31                                                 NaN

                                                              \
             PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)
Ano  Mês Dia
2003 1   1                                           -9999.0
         1                                           -9999.0
         1                                           -9999.0
         1                                           -9999.0
         1                                           -9999.0
...                                                      ...
2023 12  31                                            988.8
         31                                            987.4
         31                                            986.8
         31                                            987.0
         31                                              NaN

                                                               \
             PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)
Ano  Mês Dia
2003 1   1                                            -9999.0
         1                                            -9999.0
         1                                            -9999.0
         1                                            -9999.0
         1                                            -9999.0
...                                                       ...
2023 12  31                                             987.4
         31                                             986.7
         31                                             986.6
         31                                             986.8
         31                                               NaN

                            RADIACAO  \
             RADIACAO GLOBAL (KJ/mý)
Ano  Mês Dia
2003 1   1                   -9999.0
         1                   -9999.0
         1                   -9999.0
         1                   -9999.0
         1                   -9999.0
...                              ...
2023 12  31                   2575.3
         31                   1760.8
         31                   1127.5
         31                    490.1
         31                      NaN

                                              TEMPERATURA  \
             TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)
Ano  Mês Dia
2003 1   1                                           24.3
         1                                           24.7
         1                                           24.4
         1                                           24.1
         1                                           24.5
...                                                   ...
2023 12  31                                          34.4
         31                                          33.4
         31                                          32.5
         31                                          30.8
         31                                           NaN

                                                   \
             TEMPERATURA DO PONTO DE ORVALHO (øC)
Ano  Mês Dia
2003 1   1                                   23.3
         1                                   23.3
         1                                   23.2
         1                                   23.2
         1                                   23.4
...                                           ...
2023 12  31                                  19.4
         31                                  18.0
         31                                  21.8
         31                                  21.8
         31                                   NaN

                                                         \
             TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)
Ano  Mês Dia
2003 1   1                                         24.7
         1                                         24.7
         1                                         24.7
         1                                         24.9
         1                                         24.6
...                                                 ...
2023 12  31                                        35.2
         31                                        35.0
         31                                        33.9
         31                                        32.7
         31                                         NaN

                                                         \
             TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)
Ano  Mês Dia
2003 1   1                                         24.3
         1                                         24.3
         1                                         24.4
         1                                         24.1
         1                                         24.1
...                                                 ...
2023 12  31                                        33.9
         31                                        33.3
         31                                        32.1
         31                                        30.8
         31                                         NaN

                                                               \
             TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)
Ano  Mês Dia
2003 1   1                                               23.4
         1                                               23.4
         1                                               23.4
         1                                               23.5
         1                                               23.5
...                                                       ...
2023 12  31                                              20.6
         31                                              19.7
         31                                              22.0
         31                                              21.9
         31                                               NaN

                                                               \
             TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)
Ano  Mês Dia
2003 1   1                                            -9999.0
         1                                            -9999.0
         1                                            -9999.0
         1                                            -9999.0
         1                                            -9999.0
...                                                       ...
2023 12  31                                              19.1
         31                                              17.9
         31                                              18.0
         31                                              21.3
         31                                               NaN

                                              UMIDADE  \
             UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)
Ano  Mês Dia
2003 1   1                                       94.0
         1                                       94.0
         1                                       93.0
         1                                       95.0
         1                                       95.0
...                                               ...
2023 12  31                                      45.0
         31                                      42.0
         31                                      55.0
         31                                      59.0
         31                                       NaN

                                                       \
             UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)
Ano  Mês Dia
2003 1   1                                       92.0
         1                                       92.0
         1                                       91.0
         1                                       92.0
         1                                       93.0
...                                               ...
2023 12  31                                      40.0
         31                                      39.0
         31                                      40.0
         31                                      52.0
         31                                       NaN

                                                  \
             UMIDADE RELATIVA DO AR, HORARIA (%)
Ano  Mês Dia
2003 1   1                                  94.0
         1                                  92.0
         1                                  93.0
         1                                  95.0
         1                                  94.0
...                                          ...
2023 12  31                                 41.0
         31                                 40.0
         31                                 53.0
         31                                 59.0
         31                                  NaN

                                            VENTO                             \
             VENTO, DIREÇO HORARIA (gr) (ø (gr)) VENTO, RAJADA MAXIMA (m/s)
Ano  Mês Dia
2003 1   1                                -9999.0                    -9999.0
         1                                -9999.0                    -9999.0
         1                                -9999.0                    -9999.0
         1                                -9999.0                    -9999.0
         1                                -9999.0                    -9999.0
...                                           ...                        ...
2023 12  31                                 320.0                        6.6
         31                                 339.0                        7.0
         31                                 105.0                        6.0
         31                                  96.0                        4.0
         31                                   NaN                        NaN


             VENTO, VELOCIDADE HORARIA (m/s)
Ano  Mês Dia
2003 1   1                           -9999.0
         1                           -9999.0
         1                           -9999.0
         1                           -9999.0
         1                           -9999.0
...                                      ...
2023 12  31                              3.0
         31                              3.4
         31                              2.0
         31                              1.5
         31                              NaN

[26280 rows x 18 columns]

__Exercício 3: Analisando os DataFrame__

*  Com base nos três ``DataFrame`` carregados:
1. Analisando as colunas relacionadas e precipitações e temperaturas, compare as médias, os valores mínimos e máximos em cada um dos anos.

In [10]:
df_concat.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 26280 entries, (2003, 1, 1) to (2023, 12, 31)
Data columns (total 18 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   (HORA (UTC), )                                                    26280 non-null  object
 1   (PRECIPITAÇÃO, PRECIPITAÇÃO TOTAL, HORÁRIO (mm))                  25646 non-null  float64
 2   (PRESSAO, PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB))  25647 non-null  float64
 3   (PRESSAO, PRESSÇO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB))        25641 non-null  float64
 4   (PRESSAO, PRESSÇO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB))       25640 non-null  float64
 5   (RADIACAO, RADIACAO GLOBAL (KJ/mý))                               22169 non-null  float64
 6   (TEMPERATURA, TEMPERATURA DO AR - BULBO SECO, HORARIA (øC))       25647 non-null  float64
 7   (TEMPERATURA, TEMPERATURA DO PONTO DE ORVALHO (øC))               25647 non-null  float64
 8   (TEMPERATURA, TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC))         25641 non-null  float64
 9   (TEMPERATURA, TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC))         25641 non-null  float64
 10  (TEMPERATURA, TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC))   25641 non-null  float64
 11  (TEMPERATURA, TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC))   25641 non-null  float64
 12  (UMIDADE, UMIDADE REL. MAX. NA HORA ANT. (AUT) (%))               25641 non-null  float64
 13  (UMIDADE, UMIDADE REL. MIN. NA HORA ANT. (AUT) (%))               25641 non-null  float64
 14  (UMIDADE, UMIDADE RELATIVA DO AR, HORARIA (%))                    25647 non-null  float64
 15  (VENTO, VENTO, DIREÇO HORARIA (gr) (ø (gr)))                     22348 non-null  float64
 16  (VENTO, VENTO, RAJADA MAXIMA (m/s))                               22341 non-null  float64
 17  (VENTO, VENTO, VELOCIDADE HORARIA (m/s))                          22348 non-null  float64
dtypes: float64(17), object(1)
memory usage: 3.7+ MB

##### Encontrando a média, máxima e mínima das precipitções o dataframe.

In [11]:
coluna_precipitacao = df_concat['PRECIPITAÇÃO','PRECIPITAÇÃO TOTAL, HORÁRIO (mm)']

In [12]:
# Substituir os valores indesejados por None
coluna_precipitacao.replace({0: None, -9999.0: None}, inplace=True)

In [13]:
# Calcular a média dos valores não nulos
media_precipitacao = coluna_precipitacao.mean(skipna=True)

In [14]:
print('A precipipação média foi de',media_precipitacao, 'mm')

A precipipação média foi de 2.5692810457516244 mm

In [15]:
# Preencher os valores None na coluna com a média
coluna_precipitacao.fillna(media_precipitacao, inplace=True)

In [16]:
print(coluna_precipitacao)

Ano   Mês  Dia
2003  1    1      2.569281
           1      2.569281
           1      2.569281
           1      2.569281
           1      2.569281
                    ...
2023  12   31     2.569281
           31     2.569281
           31     2.569281
           31     2.569281
           31     2.569281
Name: (PRECIPITAÇÃO, PRECIPITAÇÃO TOTAL, HORÁRIO (mm)), Length: 26280, dtype: float64

In [17]:
# Encontrando a menor precipitação dos valores não nulos
menor_precipitacao = coluna_precipitacao.min(skipna=True)

In [18]:
print('A menor precipitação registrada doi de',menor_precipitacao, 'mm')

A menor precipitação registrada doi de 0.2 mm

In [19]:
# Encontrando a maior precipitação dos valores não nulos
maior_precipitacao = coluna_precipitacao.max(skipna=True)

In [20]:
print('A menor precipitação registrada foi de',maior_precipitacao, 'mm')

A menor precipitação registrada foi de 59.0 mm

#### Encontrando as temperaturas média, máxima e mínima das colunas com index Temperatura.

In [21]:
# Encontrando as médias das temperaturas passando as colunas como lista de listas.
colunas_temperatura = [
    ['TEMPERATURA', 'TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)'],
    ['TEMPERATURA', 'TEMPERATURA DO PONTO DE ORVALHO (øC)'],
    ['TEMPERATURA', 'TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)'],
    ['TEMPERATURA', 'TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)'],
    ['TEMPERATURA', 'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)'],
    ['TEMPERATURA', 'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)']
]

#### Métodos para processar várias colunas com informações sobre a temperatura

In [22]:
# Lista de listas para as colunas de temperatura
def calcular_media(coluna):
    return coluna.mean(skipna=True)

In [23]:
def preencher_valores_nan_com_media(coluna):
    media = calcular_media(coluna)
    return coluna.fillna(media, inplace=True)

In [24]:
def encontrar_menor_valor(coluna):
    return coluna.min(skipna=True)

In [25]:
def encontrar_maior_valor(coluna):
    return coluna.max(skipna=True)

In [26]:
def remover_valores_invalidos(coluna):
    return coluna.replace(-9999.0, None)

In [27]:
def filtrar_por_mes(df, mes):
    return df.loc[(slice(None), mes, slice(None)), :]

#### Analisando as colunas por meio do loop for.

In [28]:
def processar_colunas(df, colunas):
    for i in colunas:
        secao_nome, coluna_nome = i
        coluna = df[secao_nome][coluna_nome]
        coluna = remover_valores_invalidos(coluna)
        preencher_valores_nan_com_media(coluna)
        menor_valor = encontrar_menor_valor(coluna)
        maior_valor = encontrar_maior_valor(coluna)
        print(f'Coluna: {coluna_nome}')
        print(f'Média: {calcular_media(coluna)}')
        print(f'Menor valor: {menor_valor}')
        print(f'Maior valor: {maior_valor}')
        print(' ')

#### Exibindo temperaturas

In [29]:
# Chamando a função para processar as colunas de temperatura
processar_colunas(df_concat, colunas_temperatura)

Coluna: TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)
Média: 26.965803353538526
Menor valor: 8.9
Maior valor: 43.2

Coluna: TEMPERATURA DO PONTO DE ORVALHO (øC)
Média: 18.531531921593327
Menor valor: -4.3
Maior valor: 25.2

Coluna: TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)
Média: 27.60943307086614
Menor valor: 9.1
Maior valor: 43.3

Coluna: TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)
Média: 26.34309448818897
Menor valor: 8.8
Maior valor: 42.0

Coluna: TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)
Média: 19.053807086614174
Menor valor: -3.2
Maior valor: 25.8

Coluna: TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)
Média: 17.972182340272788
Menor valor: -6.4
Maior valor: 24.2

#### Comparando os mesmos dados do exercício anterior, mas para o mes de Janeiro de cada um dos três anos.

In [30]:
df_concat.index

MultiIndex([(2003,  1,  1),
            (2003,  1,  1),
            (2003,  1,  1),
            (2003,  1,  1),
            (2003,  1,  1),
            (2003,  1,  1),
            (2003,  1,  1),
            (2003,  1,  1),
            (2003,  1,  1),
            (2003,  1,  1),
            ...
            (2023, 12, 31),
            (2023, 12, 31),
            (2023, 12, 31),
            (2023, 12, 31),
            (2023, 12, 31),
            (2023, 12, 31),
            (2023, 12, 31),
            (2023, 12, 31),
            (2023, 12, 31),
            (2023, 12, 31)],
           names=['Ano', 'Mês', 'Dia'], length=26280)

#### Exibindo os dados das precipitações e temperaturas do mês de janeiro para os anos de 2003, 2013, 2023

In [31]:
colunas_janeiro = [
    ['PRECIPITAÇÃO','PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'],
    ['TEMPERATURA', 'TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)'],
    ['TEMPERATURA', 'TEMPERATURA DO PONTO DE ORVALHO (øC)'],
    ['TEMPERATURA', 'TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)'],
    ['TEMPERATURA', 'TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)'],
    ['TEMPERATURA', 'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)'],
    ['TEMPERATURA', 'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)']
]

In [32]:
# Chamando a função para filtrar os dados de janeiro
dados_janeiro = filtrar_por_mes(df_concat, 1)

# Chamando a função para processar as colunas de precipitação e temperatura em janeiro
processar_colunas(dados_janeiro, colunas_janeiro)

Coluna: PRECIPITAÇÃO TOTAL, HORÁRIO (mm)
Média: 2.5760246093658403
Menor valor: 0.2
Maior valor: 41.2

Coluna: TEMPERATURA DO AR - BULBO SECO, HORARIA (øC)
Média: 26.881622128457572
Menor valor: 22.1
Maior valor: 35.8

Coluna: TEMPERATURA DO PONTO DE ORVALHO (øC)
Média: 21.850914205344584
Menor valor: 12.8
Maior valor: 25.2

Coluna: TEMPERATURA MµXIMA NA HORA ANT. (AUT) (øC)
Média: 27.411908110642287
Menor valor: 22.4
Maior valor: 35.8

Coluna: TEMPERATURA MÖNIMA NA HORA ANT. (AUT) (øC)
Média: 26.348382559774965
Menor valor: 22.0
Maior valor: 35.2

Coluna: TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (øC)
Média: 22.324519456165024
Menor valor: 13.8
Maior valor: 25.8

Coluna: TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (øC)
Média: 21.175428887659113
Menor valor: 12.3
Maior valor: 24.0

#### Analisando precipitações por estações do ano.

In [33]:
def preencher_valores_nan_com_media(coluna):
    media = calcular_media(coluna)
    coluna_filled = coluna.fillna(media)
    return coluna_filled

In [34]:
colunas_relacionadas = ['PRECIPITAÇÃO']

In [35]:
estacoes = {
    'Verão': [1, 2, 3],
    'Outono': [4, 5, 6],
    'Inverno': [7, 8, 9],
    'Primavera': [10, 11, 12]
}

In [36]:
def filtrar_por_estacao(df, estacao_indices):
    return df[df.index.get_level_values(1).isin(estacao_indices)]

In [37]:
def calcular_medias_por_estacao(df, colunas, estacao_indices):
    medias_por_estacao = {}
    for estacao_nome, estacao_meses in estacao_indices.items():
        dados_estacao = filtrar_por_estacao(df, estacao_meses)
        medias_estacao = {}
        for coluna_nome in colunas:
            coluna = dados_estacao[coluna_nome].copy()
            remover_valores_invalidos(coluna)
            coluna_filled = preencher_valores_nan_com_media(coluna)
            media = calcular_media(coluna_filled)
            medias_estacao[coluna_nome] = media
        medias_por_estacao[estacao_nome] = medias_estacao
    return medias_por_estacao

In [38]:
medias_por_estacao = calcular_medias_por_estacao(df_concat, colunas_relacionadas, estacoes)

#### Exibir estações do ano com suas, respectivas, médias de precipitações

In [44]:
for estacao, medias in medias_por_estacao.items():
    print(f"Estação: {estacao}")
    for coluna, media in medias.items():
        media_float = media.mean()  # Calculando a média diretamente
        print(f"Média de {coluna}: {media_float:.5f} mm")
    print()

Estação: Verão
Média de PRECIPITAÇÃO: 2.55909 mm

Estação: Outono
Média de PRECIPITAÇÃO: 2.56047 mm

Estação: Inverno
Média de PRECIPITAÇÃO: 2.56442 mm

Estação: Primavera
Média de PRECIPITAÇÃO: 2.59283 mm